#:schema node_modules/wrangler/config-schema.json
name = "canwin"
compatibility_date = "2024-03-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "canwin-db"
database_id = "165397f8-d5bb-4b06-a5d9-a44c2c1cffc2"
migrations_dir = "migrations"
