#:schema node_modules/wrangler/config-schema.json
name = "canwin"
compatibility_date = "2024-03-11"
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "canwin_v2_final_db"
database_id = "5fea3ebe-b064-4298-852f-ab4fda9835e7"
migrations_dir = "migrations"
